name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node_version: "12.x"
      - run: npm ci # installiert unsere Dependencies = npm i
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true